return {
  {
    "hedyhli/outline.nvim",
    opts = {
      symbols = {
        icons = {
          Array = { icon = " ", hl = "@constant" },
          Boolean = { icon = "󰨙 ", hl = "@boolean" },
          Class = { icon = " ", hl = "@type" },
          Constant = { icon = "󰏿 ", hl = "@constant" },
          Constructor = { icon = " ", hl = "@constructor" },
          Enum = { icon = " ", hl = "@type" },
          EnumMember = { icon = " ", hl = "@field" },
          Event = { icon = "", hl = "@type" },
          Field = { icon = " ", hl = "@field" },
          File = { icon = " ", hl = "@text.uri" },
          Function = { icon = "󰊕 ", hl = "@function" },
          Interface = { icon = " ", hl = "@type" },
          Key = { icon = " ", hl = "@type" },
          Method = { icon = "󰊕 ", hl = "@method" },
          Module = { icon = " ", hl = "@namespace" },
          Namespace = { icon = "󰦮 ", hl = "@namespace" },
          Null = { icon = " ", hl = "@type" },
          Number = { icon = "󰎠 ", hl = "@number" },
          Object = { icon = " ", hl = "@type" },
          Operator = { icon = "", hl = "@operator" },
          Package = { icon = " ", hl = "@namespace" },
          Property = { icon = " ", hl = "@method" },
          String = { icon = " ", hl = "@string" },
          Struct = { icon = "󰆼 ", hl = "@type" },
          TypeParameter = { icon = "", hl = "@parameter" },
          Variable = { icon = "󰀫 ", hl = "@constant" },
          Component = { icon = "󰡀", hl = "@function" },
          Fragment = { icon = "", hl = "@constant" },
          TypeAlias = { icon = " ", hl = "Type" },
          Parameter = { icon = " ", hl = "Identifier" },
          StaticMethod = { icon = "󰮄", hl = "Function" },
          Macro = { icon = "󰰏", hl = "Function" },
        },
      },
      symbol_blacklist = {},
    },
  },
}
